### ISSUE TITLE
feature: Support syncing projects back to the template

### ISSUE THREAD

**Issue by mircea-pavel-anton** [hay-kot/scaffold#221]
Similar to how we can use `cruft` to sync a `cookiecutter` repo back to the original template, I think it would be useful to implement something similar in scaffold.

My usecase for this is that I have a monorepo of various repo templates and I sometimes update them by adding new workflows or making various changes. It would be helpful to allow downstream repos to update themselves back to the upstream template to propagate those changes automatically

**Comment by alexeagle** [comment]
I think this is the same request as https://github.com/hay-kot/scaffold/discussions/173

**Comment by mircea-pavel-anton** [comment]
Indeed it is! I did not think to look into discussions for this 😅 

Should I close this as a duplicate?
