### ISSUE TITLE
scaffold command fails on fresh install

### ISSUE THREAD

**Issue by tekpriest** [hay-kot/scaffold#89]
## Steps
- Follow the instructions on the docs to install scaffold cli using homebrew
- Make a new directory
- Run `scaffold new project`

## Result
`8:54AM FTL failed to run scaffold error="failed to parse scaffoldrc file: EOF"`

## Expected Result
Generates a project

**Comment by hay-kot** [comment]
Ahh, That's not a good look. Just pushed a fix, should be in the next build shortly. Thanks for letting me know!
